### ISSUE TITLE
error during running

### ISSUE THREAD

**Issue by mohamadmarjani97** [jeffdelmerico/pointcloud_tutorial#1]
hi
I want to use your code in pcl 1.6 and visual studio 2010, after I built this code with cmake 3.16 I opened sln files in visual 2010 and when I run each code I got this error:
"
Error	1	error D8021: invalid numeric argument '/Wno-deprecated-declarations'	D:\3D Change detection\pointcloud_tutorial-master\build\cl	pcl_template_matching
"
I want to know can you help me to use this codes?
thanks

**Comment by jeffdelmerico** [comment]
Hi.  Apologies that my response is coming so late.  This repository is not actively maintained.  

I hope that you were able to resolve your issue.  The code here was targeting linux distributions based on the dependencies, and I have not tried to compile it on Windows.  I don't have enough experience with Visual Studio to offer any advice on how to resolve this error.   But from this [stackoverflow question](https://stackoverflow.com/questions/13717551/1cl-command-line-error-d8021-invalid-numeric-argument-wno-deprecated-er), it looks like you can just remove the -Wno-deprecated-declaration flag in the build settings.
